apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mestier-rustfs
  labels:
    app.kubernetes.io/name: mestier-rustfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
